name: mechint
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # ---- Core ----
  - python=3.10
  - pip=24.2.0
  - numpy<2

  # ---- PyTorch + CUDA ----
  - pytorch=2.2.2
  - cpuonly=2.0
  - torchvision=0.17.2
  - torchaudio=2.2.2

  # ---- Pip packages ----
  - pip:
      - pytorch-lightning==2.2.5
      - tensorboard==2.17.1
      - transformer-lens==1.12.0
      - pytest>=8.0.0
      - typeguard>=4.0.0

      - tabulate>=0.9.0
      - tqdm>=4.66.5
      - pillow>=10.4.0
      - notebook>=7.2.2
      - jupyterlab>=4.2.5
      - matplotlib>=3.8.0
      - seaborn>=0.13.2
      - ipywidgets>=8.1.2

      - transformers==4.39.3
      - accelerate>=0.27.0
      - datasets>=2.18.0
      - sentencepiece>=0.2.0